server.port=${PORT:8080}

sap.baseUrl=${SAP_BASEURL}
sap.username=${SAP_USERNAME}
sap.password=${SAP_PASSWORD}

sap.openLikeStatuses=${SAP_OPENLIKESTATUSES:Z2,Z3,01,Z7,Z8,Z6,Z1}
sap.pageSize=${SAP_PAGESIZE:200}

assignment.scheduler.delayMs=${ASSIGNMENT_DELAY_MS:30000}
assignment.scheduler.initialDelayMs=${ASSIGNMENT_INITIAL_DELAY_MS:10000}