server.port=8080

# Base tenant URL (NO trailing slash)
sap.baseUrl=https://my1002247.us1.test.crm.cloud.sap

# Basic auth (Service user)
sap.username=SERVICECLOUD_CASE_USER
sap.password=SCv2CASEapiUSER2026SecurePASS!!9845

# Case statuses that represent "OPEN or IN_PROCESS" across BOTH schemas
# (Edit these to match SpeedX final decision)
# Example from your screenshots:
# - Claims schema: Z2 New (OPEN), 01 Open (OPEN), Z7 In Progress (IN_PROCESS), Z8 Awaiting Customer (IN_PROCESS), Z6 On Hold (IN_PROCESS)
# - Operations schema: Z2 New (OPEN), Z3 Open (OPEN), Z1 On Hold (IN_PROCESS) etc.
sap.openLikeStatuses=Z2,Z3,01,Z7,Z8,Z6,Z1

# Paging
sap.pageSize=200

# Scheduler - current set to every 2 mins to reduce api calls
assignment.scheduler.delayMs=120000
assignment.scheduler.initialDelayMs=10000